language: r
cache: packages
r: devel
warnings_are_errors: false
sudo: required

addons:
 apt:
  packages:
    - r-cran-tkrplot
    - tk-dev

r_check_args: "--as-cran"

notifications:
  email:
    on_success: change
    on_failure: change